### ISSUE TITLE
Writting own kernel function

### ISSUE THREAD

**Issue by Patrick-Lascombe** [gstavrinos/ros_opencl#1]
Hello, 
First of all thank you for this tool, I'm trying to test it right now and I need a specific 'process' function that is not implemented yet.

The argument of that function are : 3 doubles that will be constants through all the iterations and 1 vector of doubles.

From what I understood, I need to write a new 'process' function in ros_opencl.cpp that inplements these parameters and then another function in test_kernels.cl in which the code is implemented.

But can we give a variable that will be constant throughout all the iteration to a kernel function and if it is the case how to I write it ?

Thanks for your help, 
Hope to hear from you soon

**Comment by Patrick-Lascombe** [comment]
Found it by myself through testing and reading some documentation

**Comment by gstavrinos** [comment]
Hey Patrick,

Thanks for the interest in the package, and sorry for the late reply. I was on holidays, with very limited internet access. Can you please provide me with your solution or submit a PR that includes your required functions?

Thanks,

George
